project_id: '651662'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    en-US: en-US
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: *languages_mapping
  # - source: /versioned_docs/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
  #   languages_mapping: *languages_mapping
  # - source: /community/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
  #   languages_mapping: *languages_mapping
  # - source: /eco-integration/**/*
  #   translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs-eco-integration/current/**/%original_file_name%
  #   languages_mapping: *languages_mapping
