project_id: '664454'
api_token_env: CROWDIN_PERSONAL_TOKEN
languages_mapping:
  two_letters_code:
    en-US: en-US
preserve_hierarchy: 1
files:
  - source: /docs/**/*
    ignore:
      - /docs/reference/concept_design/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /versioned_docs/**/*
    ignore:
      - version-2.3.2/
      - /versioned_docs/*/reference/concept_design/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/**/%original_file_name%
